-- Proyecto TOTEM AEROPUERTO
-- Topic Avanzados de Base de datos

-- Integrante: 
-- Gianfranco Astorga
-- Ernesto Starck
-- Sebastián Bustamante
-- David Ñanculeo

-- Creación del usuario en Oracle

CREATE USER admin IDENTIFIED BY admin;
GRANT ALL PRIVILEGES TO admin;

DROP TABLE PAIS;
DROP TABLE CIUDAD;
DROP TABLE AEROPUERTO;
DROP TABLE VUELO;
DROP TABLE PASAJERO;
DROP TABLE COMPRA;
DROP TABLE RESERVA;
DROP TABLE AEROLINEA;
DROP TABLE TRIPULACION;
DROP TABLE VUELO_TRIPULACION;
DROP TABLE SERVICIOS;

CREATE TABLE PAIS(
    id_pais NUMBER NOT NULL,
    nombre VARCHAR2(99) NOT NULL,
    CONSTRAINT PK_PAIS PRIMARY KEY (id_pais)
);

CREATE TABLE CIUDAD(
    id_ciudad NUMBER NOT NULL,
    nombre VARCHAR2(99) NOT NULL,
    id_pais NUMBER NOT NULL,
    CONSTRAINT PK_CIUDAD PRIMARY KEY (id_ciudad),
    CONSTRAINT FK_CIUDAD_PAIS FOREIGN KEY (id_pais) REFERENCES PAIS(id_pais)
    ON DELETE CASCADE
);

CREATE TABLE AEROPUERTO(
    id_aeropuerto NUMBER NOT NULL,
    nombre VARCHAR2(99) NOT NULL,
    id_ciudad NUMBER NOT NULL,
    CONSTRAINT PK_AEROPUERTO PRIMARY KEY (id_aeropuerto),
    CONSTRAINT FK_AEROPUERTO_CIUDAD FOREIGN KEY (id_ciudad) REFERENCES CIUDAD(id_ciudad)
    ON DELETE CASCADE
);

CREATE TABLE AEROLINEA(
    id_aerolinea NUMBER NOT NULL,
    nombre_aerolinea VARCHAR2(99) NOT NULL,
    CONSTRAINT PK_AEROLINEA PRIMARY KEY (id_aerolinea)
);



